### ISSUE TITLE
Add image handling for items

### ISSUE THREAD

**Issue by jackgoldsmith4** [cssgunc/carolinacloset#23]
- storing images for many items
- Uploading/downloading of stored images
- adding images to the frontend items table

**Comment by Dafondo** [comment]
I think we'll be storing images directly in the PostgreSQL database. We're running on CloudApps and, as far as I can tell, they have no non-DB storage options. Some things to consider:
1. Use a library (eg. [Sharp](https://github.com/lovell/sharp), [Jimp](https://www.npmjs.com/package/jimp)) to resize and optimize image quality. We only have 2GB of PostgreSQL storage by default, but may be able to request more from the CloudApps team.
2. Use lazy loading so we're not loading all the images at once (eg. [vanilla-lazyload](https://www.npmjs.com/package/vanilla-lazyload)).

I'll take a stab at it.

**Comment by jackgoldsmith4** [comment]
@AdamWinek frontend stuff for this:
- getting images from the DB and displaying them on cards / item views on the frontend
- adding image upload capabilities for editing items

Austin has some examples in #27

**Comment by jackgoldsmith4** [comment]
fixed in #36!
