### ISSUE TITLE
Add full editing capabilities to `/entry/search` cards

### ISSUE THREAD

**Issue by jackgoldsmith4** [cssgunc/carolinacloset#38]
Right now, clicking on the edit button for a card in this view only allows the user to edit the name. There should be fields for
- Color
- Sizing info (based on the type of item)
- Image (new image upload)
- Gender / Brand: not sure about these because they are only used for the name, and the name is editable.

**Comment by AdamWinek** [comment]
You could definetly copy a lot of code from manual/entry to solve this issue
